configfile: "config/config.yaml"
ra_config = config["repeat_annotator"]
slurm_config = config["slurm"]

rule repeatmasker:
    input:
        genome = lambda wc: f"{ra_config['genome_dir']}/{os.listdir(ra_config['genome_dir'])[0]}",
        repeat_lib = ra_config["repeat_lib"]
    output:
        masked = "results/repeat_annotator/{}.masked".format(os.path.basename(ra_config['genome_dir']))
    log:
        "logs/repeat_annotator/repeatmasker.log"
    params:
        output_dir = "results/repeat_annotator"
    conda:
        ra_config["conda_env"]
    resources:
        partition = slurm_config["default"]["partition"],
        time = slurm_config["repeat"]["repeatmasker"]["time"],
        cpus = slurm_config["repeat"]["repeatmasker"]["cpus"],
        mem = slurm_config["repeat"]["repeatmasker"]["mem"]
    shell:
        """
        RepeatMasker -s -lib {input.repeat_lib} {input.genome} -pa {resources.cpus} \
                     -dir {params.output_dir} 2>> {log}
        """