configfile: "config/config.yaml"
ra_config = config["repeat_annotator"]
slurm_config = config["slurm"]

rule repeatmasker:
    input:
        genome = lambda wc: os.path.join("data", "genome", os.listdir(os.path.join("data", "genome"))[0]) if os.path.exists(os.path.join("data", "genome")) else "",
        repeat_lib = lambda wc: os.path.join("data", "repeats", "mosquito_repeat_lib.fasta")
    output:
        masked = "results/repeat_annotator/genome.masked"
    log:
        "logs/repeat_annotator/repeatmasker.log"
    params:
        output_dir = "results/repeat_annotator"
    conda:
        ra_config["conda_env"]
    resources:
        partition = slurm_config["default"]["partition"],
        time = slurm_config["repeat"]["repeatmasker"]["time"],
        cpus = slurm_config["repeat"]["repeatmasker"]["cpus"],
        mem = slurm_config["repeat"]["repeatmasker"]["mem"]
    shell:
        """
        RepeatMasker -s -lib {input.repeat_lib} {input.genome} -pa {resources.cpus} \
                     -dir {params.output_dir} 2>> {log}
        """