configfile: "config/config.yaml"
ma_config = config["maker_annotator"]
slurm_config = config["slurm"]

rule braker:
    input:
        genome = lambda wc: f"{ma_config['genome_dir']}/{os.listdir(ma_config['genome_dir'])[0]}",
        bam = ma_config["bam_file"],
        sif = ma_config["sif_path"]
    output:
        gff3 = f"{ma_config['output_dir']}/braker/augustus.hints.gff3"
    log:
        f"{ma_config['log_dir']}/braker.log"
    resources:
        partition = slurm_config["default"]["partition"],
        time = slurm_config["maker"]["braker"]["time"],
        cpus = slurm_config["maker"]["braker"]["cpus"],
        mem = slurm_config["maker"]["braker"]["mem"]
    shell:
        """
        singularity exec {input.sif} braker.pl --genome={input.genome} --bam={input.bam} \
            --species={ma_config['species_name']} --cores={resources.cpus} \
            --workingdir={ma_config['output_dir']}/braker 2>> {log}
        """