executor: slurm
jobs: 15
use-conda: true
latency-wait: 60
default-resources:
  partition: day-long-cpu
  time: 24:00:00
  mem: 64G
  cpus: 16
cluster-config:
  mkdir -p logs/{rule}/{wildcards}
  sbatch 
  --partition={resources.partition}
  --time={resources.time}
  --cpus-per-task={resources.cpus}
  --mem={resources.mem}
  --output=logs/{rule}/{wildcards}.slurm.out
  --error=logs/{rule}/{wildcards}.slurm.err
